import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import UserProvider from "@/context/UserContext";
import styles from "./layout.module.css";
import Sidebar from "@/components/sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.container}>
          <UserProvider>
            <Sidebar/>
            <div className={`layout-container ${styles.main}`}>
              {children}
            </div>
          </UserProvider>
        </div>
      </body>
    </html>
  );
}
