import "../globals.css";

export const metadata = {
  title: "Create Next App without layout.js",
  description: "Generated by create next app without layout.js",
};

export default function LoginLayout({ children }) {
  // 루트 레이아웃 없이 로그인 페이지에 대한 레이아웃만 적용
  return (
    <html lang="ko">
      <body>
        {children}
      </body>
    </html>
  );
}